#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
  echo "
USAGE: $0 <any git subcommand>

Example: cgh pr list
"
  exit 1
fi

c_repos=$(cgit remote -v | grep github.com | awk -F":| |.git " '{print $2}' | uniq)
c_basedir=${PWD}

if [[ "$@" =~ "--json" ]]; then

  for repo in ${c_repos}; do
    gh --repo ${repo} "$@"
  done

else

  for repo in ${c_repos}; do
    echo "## [${repo}] "
    gh --repo ${repo} "$@"
    echo -e ""
  done

fi
