#!/usr/bin/env bash

c_repos=$(find -L . -maxdepth 2 -name .git -type d -print | cut -d'/' -f2 | sort)
c_basedir=${PWD}
export GIT_PAGER="cat"

for repo in ${c_repos}; do
  echo "## [${repo}] "
  git --git-dir="${c_basedir}/${repo}/.git" \
    --work-tree="${c_basedir}/${repo}" \
    "$@"
  echo -e ""
done

