#!/usr/bin/env bash

c_repos=$(find -L . -maxdepth ${CGIT_DEPTH:-2} -name .git -type d -print | sed -e 's/\.\///g' | sed -e 's/\/.git$//g' | sort)
c_basedir=${PWD}
export GIT_PAGER="cat"

for repo in ${c_repos}; do
  echo "## [${repo}] "
  git --git-dir="${c_basedir}/${repo}/.git" \
    --work-tree="${c_basedir}/${repo}" \
    "$@"
  echo -e ""
done

