#!/usr/bin/env bash
#
# This script creates a backup config file from all repositories in a given path.
# The config file stores the local path and the remote url

set -e
set -o pipefail

if [[ $# -lt 2 ]]; then
  echo "USAGE: $0 <backup file location> <git base path> [<maximum search depth>]"
  exit 1
fi

# Set backup file location
readonly BACKUP_FILE="${1}"

# Set the Git Path from user input
readonly GITPATH="${2}"

# Set the max search depth from user input, add one level for .git subdir matching
max_search_depth_user_arg="${3:-2}"
readonly MAX_SEARCH_DEPTH=$((max_search_depth_user_arg += 1))

if [[ ! -d ${GITPATH} ]]; then
  echo "ERROR: ${GITPATH} is not a directory. Exiting.."
  exit 1
fi

# Collect top-level git directories
repolist=$(find ${GITPATH} -maxdepth ${MAX_SEARCH_DEPTH} -type d -name .git | awk -F"/.git" '{print $1}')

# Create the backup
for repo in ${repolist}; do
  repo_dir="${repo#${GITPATH}/}"
  repo_remote="$(git --git-dir=${repo}/.git --work-tree=${repo} remote get-url origin)"
  echo "${repo_dir} ${repo_remote}"
done >${BACKUP_FILE}
