#!/usr/bin/env bash
set -e
set -o pipefail

if [[ $# -ne 1 ]]; then
  echo "USAGE: $0 foo.example.com"
  exit 1
fi

readonly C_SSLDOMAIN="${1}"

# shellcheck disable=SC2086,SC2196
for san in $(echo q | openssl s_client -connect ${C_SSLDOMAIN}:443 -servername ${C_SSLDOMAIN} 2>/dev/null | openssl x509 -noout -text | egrep "DNS:" | tr -d "DNS:,"); do
  echo -n "$san  "
  dig +short +fail $san | tail -1
  echo ""
done | egrep -v "^$" | sort -k 2 | awk '{printf "%40s : %s\n", $1, $2}'
